[theme]
primaryColor = "#1a6d8e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#d9d9d9"
textColor = "#12303b"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
